#!/bin/bash

##################################################################
# Author       : Sinesio Bittencourt
# Email        : contato@sinesio.com.br
# Info         : restore_all_users_reseller (cpmove in server)
# Version      : 0.1 ( beta )
# Project      : http://git.sinesio.com.br
##################################################################
VERSAO="0.1b"

#restore_all_users_reseller
for user in $(cat /etc/trueuserowners | grep $USER_DA_REVENDA | cut -d: -f1); do /scripts/pkgacct --skip-limit $user .;  done
